[package]
name = "grip"
version = "1.0.0"
authors = ["Jens Reidel <jens@troet.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
walkdir = "2"
regex = "1.3.1"
colored = "1.8.0"
atty = "0.2.13"
